spin_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "example-display"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "serve-spa"
source = "serve-spa/target/spin-http-js.wasm"
files = ["front-end/spin-example-showcase/dist/index.html"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
workdir = "serve-spa"

[[component]]
id = "static-files"
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm", digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375" }
files = [ { source = "front-end/spin-example-showcase/dist/assets", destination = "/" } ]
[component.trigger]
route = "/assets/..."

[[component]]
id = "api"
source = "api-server/target/spin-http-js.wasm"
allowed_http_hosts = ["http://localhost:5501", "https://raw.githubusercontent.com"]
files = ["auth.json"]
[component.trigger]
route = "/api/..."
[component.build]
workdir = "api-server"
command = "npm run build"

